blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog import views


app_name = 'blog'


urlpatterns = [
    path('', cache_page(60)(views.FashionBlogListView.as_view()), name='blog'),
    path('developing_posts/', views.DevelopingPostsListView.as_view(), name='developing_posts'),
    path('create/', views.PostCreateView.as_view(), name='blog_create'),
    path('<slug:blog_slug>/', cache_page(60)(views.BlogDetailView.as_view()), name='blog_detail'),
    path('edite/<slug:blog_slug>/', views.ReleasePostUpdateView.as_view(), name='release_post'),
    path('developing_posts/delete/<slug:blog_slug>', views.PostDeleteView.as_view(), name='post_delete'),
    path('activity/<slug:blog_slug>', views.TogglePublishedStatusView.as_view(), name='toggle_published_status'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('auth/', include('users.urls', namespace='users')),
    path('__debug__/', include("debug_toolbar.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models/fashion_blog.py
from django.db import models
from django.urls import reverse_lazy
from slugify import slugify


NULLABLE = {'blank': True, 'null': True}


class FashionBlog(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    content = models.TextField(blank=True, verbose_name='Содержимое')
    image = models.ImageField(upload_to='images/blog', verbose_name='Превью', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return f"Заголовок: {self.title}"

    def get_absolute_url(self):
        # return reverse_lazy('blog:blog_detail', kwargs={'blog_slug': self.slug}) - если в контроллере слаг
        if self.is_published:
            return reverse_lazy('blog:blog')
        else:
            return reverse_lazy('blog:developing_posts')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        if self.slug != slugify(self.title):
            self.slug = slugify(self.title)

        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блог'
        ordering = ('pk',)

blog/forms.py
from django import forms
from blog.models import FashionBlog


class CreatePostForm(forms.ModelForm):

    class Meta:
        model = FashionBlog
        exclude = ('slug', 'created_at', 'view_count',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 100, 'rows': 10}),
            'is_published': forms.NullBooleanSelect(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic, View
from blog.forms import CreatePostForm
from blog.models import FashionBlog


class FashionBlogListView(generic.ListView):
    queryset = FashionBlog.objects.filter(is_published=True)
    template_name = 'blog/blog.html'


class DevelopingPostsListView(LoginRequiredMixin, generic.ListView):
    queryset = FashionBlog.objects.filter(is_published=False)
    template_name = 'blog/developing_posts.html'


class BlogDetailView(generic.DetailView):

    model = FashionBlog
    template_name = 'blog/blog_detail.html'
    slug_url_kwarg = 'blog_slug'

    def get_queryset(self):
        return FashionBlog.objects.filter(slug=self.kwargs['blog_slug'])

    def get_object(self, queryset=None):
        post = super().get_object()
        post.view_count += 1
        post.save()
        return post


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = 'blog.add_fashionblog'
    form_class = CreatePostForm
    template_name = 'blog/add_post.html'


class ReleasePostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = FashionBlog
    form_class = CreatePostForm
    template_name = 'blog/add_post.html'
    slug_url_kwarg = 'blog_slug'

    def get_queryset(self):
        return FashionBlog.objects.filter(slug=self.kwargs['blog_slug'])


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = FashionBlog
    template_name = 'blog/confirm_delete_blog.html'
    slug_url_kwarg = 'blog_slug'
    success_url = reverse_lazy('blog:developing_posts')

    def get_queryset(self):
        return FashionBlog.objects.filter(slug=self.kwargs['blog_slug'])


class TogglePublishedStatusView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'blog.change_fashionblog'

    def get(self, request, blog_slug):
        post = get_object_or_404(FashionBlog, slug=blog_slug)

        if post.is_published:
            post.is_published = False
        else:
            post.is_published = True

        post.save()

        if post.is_published:
            return redirect(reverse('blog:blog'))
        else:
            return redirect(reverse('blog:developing_posts'))

blog/templates/blog/add_post.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
{% if object %}
Редактировать статью
{% else %}
Добавить статью
{% endif %}
{% endblock %}
{% block content %}
<div class="col">
    <div class="d-flex justify-content-around align-items-fluid">
        <div class="container ">
            <div class="card-body card-body-sm ">

                <div class="card-body ">
                    Добавление новой статьи в блог
                </div>


                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="alert alert-warning" role="alert">
                        <strong>Внимание!</strong> Проверь статью перед публикацией.
                    </div>
                    <div>
                        {% if object %}
                        <button type="submit" class="btn btn-outline-success">Сохранить изменения</button>
                        <a href="{% url 'blog:developing_posts' %}" class="btn btn-outline-primary">Отмена</a>
                        {% else %}
                        <button type="submit" class="btn btn-outline-success">Добавить статью</button>
                        <a href="{% url 'blog:blog' %}" class="btn btn-outline-primary" >Отмена</a>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog.html
{% extends 'catalog/base.html' %}
{% block title %}
SkyStore Blog
{% endblock %}
{% block content %}
{% load catalog_tags %}
{% for object in object_list %}
<div class="card-body mb-4 rounded-3 ">

    <div class="jumbotron jumbotron-fluid">

        <div class="container">

            <div class="card">
                <p class="card-text">
                <h2>{{ object.title }}</h2>

                <img class="rounded mx-auto d-block" src="{{ object.image|upload_media }}" alt="Post Image"
                     width="30%"
                     height="60%">

                <p class="text-black-50">Количество просмотров: {{ object.view_count }}</p>

                <div class="btn-group btn-group-sm" role="group" aria-label="Button group">
                    {% if user.is_superuser or perms.blog.change_fashionblog %}
                        <a href="{% url 'blog:blog_detail' object.slug %}" class="btn btn-outline-primary">Читать
                            статью</a>
                        <a href="{% url 'blog:toggle_published_status' object.slug %}" class="btn btn-outline-primary">Снять
                            с публикации</a>
                    {% else %}
                        <a href="{% url 'blog:blog_detail' object.slug %}" class="btn btn-outline-primary">Читать
                            статью</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% if not object_list %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">SkyStore Blog</h4><br>
        <h6 class="card-subtitle mb-2 text-muted">Тут будут отображаться все опубликованные статьи</h6>
        <p class="card-text">
            В данный момент Опубликованный статей нет
        </p>
    </div>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
{{ object.title }}
{% endblock %}
{% block content %}
{% if object %}
<div class="row row-cols-2 row-cols-md-2 mb-3 text-center">

    <div class="container justify-content-around">

        <div class="jumbotron jumbotron-fluid">
            <div class="container justify-content-around">
                <div class="card">
                    <h1 class="display-3">{{ object.title }}</h1>

                    <img class="rounded mx-auto d-block" src="{{ object.image|upload_media }}" alt="Post Image"
                         width="80%"

                         height="600">
                </div>

                <p class="lead"><br>{{ object.content }}</p>
                <a href="{% url 'blog:blog' %}" class="btn btn-outline-primary">Назад</a>
            </div>

        </div>
    </div>
</div>

{% endif %}
{% endblock %}

blog/templates/blog/confirm_delete_blog.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
Удалить статью
{% endblock %}
{% block content %}
<div class="col">
    <div class="d-flex justify-content-around align-items-fluid">
        <div class="container ">
            <div class="card-body card-body-sm ">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-danger">Подтверждение удаления</h4>
                            <h6 class="card-subtitle mb-2">Внимание!</h6>
                            Происходит удаление блога "{{ object.title }}"
                            <p class="card-text">
                                Удаленный пост не подлежит восстановлению, убедитесь в необходимости удаления
                            </p>
                            <button type="submit" class="btn btn-outline-success">Подтвердить удаление</button>
                            <a href="{% url 'blog:developing_posts' %}" class="btn btn-outline-primary">Отмена</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/deleting_confirm.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
Удалить статью
{% endblock %}
{% block content %}
<div class="col">
    <div class="d-flex justify-content-around align-items-fluid">
        <div class="container ">
            <div class="card-body card-body-sm ">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-danger">Подтверждение удаления</h4>
                            <h6 class="card-subtitle mb-2">Внимание!</h6>
                            Происходит удаление блога "{{ object.title }}"
                            <p class="card-text">
                                Удаленный пост не подлежит восстановлению, убедитесь в необходимости удаления
                            </p>
                            <button type="submit" class="btn btn-outline-success">Подтвердить удаление</button>
                            <a href="{% url 'blog:developing_posts' %}" class="btn btn-outline-primary">Отмена</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/developing_posts.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
В редакции
{% endblock %}
{% block content %}
{% for object in object_list %}
<div class="card-body mb-4 rounded-3 ">

    <div class="jumbotron jumbotron-fluid">

        <div class="container">

            <div class="card">
                <p class="card-text">
                <h2>{{ object.title }}</h2>

                <img class="rounded mx-auto d-block" src="{{ object.image|upload_media }}" alt="Post Image"
                     width="30%"
                     height="90%">
                <p class="lead"> Содержание: <br>{{ object.content|truncatechars:200 }}</p>
                <p class="lead">Признак публикации: Пост не опубликован<br></p>

                    {% if user.is_superuser or perms.blog.change_fashionblog %}
                        <div class="alert alert-warning" role="alert">
                        <strong>Внимание!</strong> Проверь статью перед публикацией.
                            <a href="{% url 'blog:release_post' object.slug %}" type="submit"
                               class="btn btn-outline-success">Перейти к проверке</a>
                            <a href="{% url 'blog:toggle_published_status' object.slug %}" class="btn btn-outline-warning">Опубликовать</a>
                    {% endif %}

                    {% if user.is_superuser or perms.blog.delete_fashionblog %}
                        <a href="{% url 'blog:post_delete' object.slug %}" class="btn btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% if not object_list %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">SkyStore Blog</h4><br>
        <h6 class="card-subtitle mb-2 text-muted">Тут будут отображаться неопубликованные посты</h6>
        <p class="card-text">
            В данный момент неопубликованных постов нет
        </p>
    </div>
</div>
{% endif %}
{% endblock %}