blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog import views


app_name = 'blog'


urlpatterns = [
    path('', cache_page(60)(views.FashionBlogListView.as_view()), name='blog'),
    path('developing_posts/', views.DevelopingPostsListView.as_view(), name='developing_posts'),
    path('create/', views.PostCreateView.as_view(), name='blog_create'),
    path('<slug:blog_slug>/', cache_page(60)(views.BlogDetailView.as_view()), name='blog_detail'),
    path('edite/<slug:blog_slug>/', views.ReleasePostUpdateView.as_view(), name='release_post'),
    path('developing_posts/delete/<slug:blog_slug>', views.PostDeleteView.as_view(), name='post_delete'),
    path('activity/<slug:blog_slug>', views.TogglePublishedStatusView.as_view(), name='toggle_published_status'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog import views

app_name = 'catalog'


urlpatterns = [
    path('', views.IndexListView.as_view(), name='homepage'),
    path('contacts/', cache_page(60)(views.ContactsView.as_view()), name='contacts'),
    path('catalog/create/', views.ProductCreateView.as_view(), name='create_product'),
    path('catalog/category/<int:cat_id>', views.show_category, name='show_category'),
    path('catalog/<slug:product_slug>/', views.ToggleSalesStatusView.as_view(), name='toggle_status'),
    path('catalog/view/<slug:product_slug>/', cache_page(60)(views.ProductDetailView.as_view()), name='product_info'),
    path('catalog/delete/<slug:product_slug>', views.ProductDeleteView.as_view(), name='delete_product'),
    path('catalog/edit/<slug:product_slug>/', views.ProductUpdateView.as_view(), name='edit_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('auth/', include('users.urls', namespace='users')),
    path('__debug__/', include("debug_toolbar.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from users.views import RegistrationView, ProfileView, ConfirmView, gen_password


app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),

    path('registration/', RegistrationView.as_view(), name='registration'),
    path('verify/<key>/', ConfirmView.as_view(), name='confirm'),
    path('registration/notification/',
         TemplateView.as_view(template_name='users/reg_notification.html'), name='notification'),
    path('reg-success/', TemplateView.as_view(template_name='users/reg_success.html'), name='reg_success'),

    path('profile/', ProfileView.as_view(), name='profile_edit'),
    path('profile/gen-password', gen_password, name='gen_password')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from blog.models.fashion_blog import NULLABLE


class User(AbstractUser):
    username = None

    first_name = models.CharField(max_length=25, verbose_name='Имя')
    last_name = models.CharField(max_length=25, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=25, verbose_name='Отчество', **NULLABLE)

    avatar = models.ImageField(upload_to='images/users', verbose_name='Автар', **NULLABLE)
    phone_number = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='Страна', **NULLABLE)
    email = models.EmailField(unique=True, verbose_name='Электронная почта')

    is_active = models.BooleanField(default=False, verbose_name='Активирован')
    verification_key = models.CharField(default='Не верифицирован', verbose_name='Ключ активации')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        is_active = False
        fields = ('first_name', 'last_name', 'patronymic', 'email', 'password1', 'password2',)
        help_texts = {
            'patronymic': 'Данное поле опционально',
        }
        error_messages = {
            'email': {
                'unique': "Указанная электронная почта уже используется.",
            },
        }


class ProfileEditForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone_number', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from random import randint
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from config import settings
from users.forms import UserRegistrationForm, ProfileEditForm
from users.models import User
from users.services import send_new_password


class RegistrationView(generic.CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:notification')

    def form_valid(self, form):
        self.object = form.save()
        self.object.verification_key = ''.join([str(randint(0, 9))
                                                for _ in range(21)])

        send_mail(
            subject='Поздравляем с регистрацией',
            message=f'Для завершения регистрации, пожалуйста, перейдите по указанной ссылке '
                    f'http://127.0.0.1:8000/auth/verify/{self.object.verification_key}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email]
        )
        return super().form_valid(form)


class ConfirmView(generic.TemplateView):

    def get(self, *args, **kwargs):
        key = self.kwargs.get('key')
        user = User.objects.filter(verification_key=key).first()
        if user:
            user.is_active = True
            user.verification_key = key
            user.save()
            login(self.request, user)
        return redirect('users:reg_success')


class ProfileView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = ProfileEditForm
    success_url = reverse_lazy('users:profile_edit')
    template_name = 'users/profile_edit.html'

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def gen_password(request):
    new_password = ''.join([str(randint(0, 9)) for _ in range(9)])
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('users:login'))

users/templates/users/logged_out.html
{% extends "catalog/base.html" %}
{% block title %}Выход{% endblock %}
{% block content %}
<h1>Выход</h1>
<p>
    Вы успешно вышли из профиля вашего аккаунта.<br>
    Вы можете <a href="{% url 'users:login' %}">авторизоваться повторно</a>.
</p>
{% endblock %}

users/templates/users/login.html
{% extends "catalog/base.html" %}
{% block title %}Авторизация{% endblock %}
{% block content %}
<h1>Авторизация</h1>
<p>Пожалуйста, заполните поля для авторизации:</p>
<div class="login-form">
    <form action="{% url 'users:login' %}" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <p><input type="submit" value="Войти"></p>
    </form>
</div>
{% endblock %}

users/templates/users/profile_edit.html
{% extends "catalog/base.html" %}
{% block title %}Аккаунт{% endblock %}
{% block content %}
<div class="container">
    <div class="card-title">
        <h1>Редактирование профиля</h1>
        <p>Чтобы зарегистрировать новый аккаунт, пожалуйста, заполните форму:</p>
    </div>

    <form method="post" enctype="multipart/form-data">

        <div class="card-body">
            {{ form.as_p }}
            {% csrf_token %}
        </div>

        <div class="card-footer">
            <div class="btn-group btn-group-sm" role="group" aria-label="Button group">
                <input type="submit" value="Сохранить изменения">
                <a href="{% url 'catalog:homepage' %}" class="btn btn-outline-primary">На главную</a>
                <a href="{% url 'users:gen_password' %}" class="btn btn-outline-primary">Получить новый пароль</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reg_notification.html
{% extends "catalog/base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h1>Почти закончили</h1>
    </div>
    <div class="card-body">
        <p>
            Для успешного завершения процесса регистрации, на указанную вами электронную почту было направлено
            письмо.<br>
            При переходе по указанной в письме ссылке, вы будете автоматически авторизованы в вашем аккаунте.
        </p>
    </div>
</div>
{% endblock %}

users/templates/users/reg_success.html
{% extends "catalog/base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="container">

    <div class="card">

        <div class="card-header">
            <h3>Регистрация завершена</h3>
        </div>

        <div class="card-body">
            <p>
                Благодарим вас за регистрацию в нашем сервисе.<br>
                Вы были автоматически авторизованы в вашем профиле.<br>
                Теперь вам доступны расширенные возможности в зависимости от ваших полномочий.
            </p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "catalog/base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="container">

    <div class="card">

        <div class="card-header">
            <h3>Регистрация</h3>
        </div>

        <form method="post">
            <div class="card-body">
                <p>Чтобы зарегистрировать новый аккаунт, пожалуйста, заполните форму:</p>
                {{ form.as_p }}
                {% csrf_token %}
            </div>

            <div class="card-footer">
                <div class="btn-group btn-group-sm" role="group" aria-label="Button group">
                    <input type="submit" value="Зарегистрироваться">
                    <a href="{% url 'catalog:homepage' %}" class="btn btn-outline-primary">Отменить</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}