blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog import views


app_name = 'blog'


urlpatterns = [
    path('', cache_page(60)(views.FashionBlogListView.as_view()), name='blog'),
    path('developing_posts/', views.DevelopingPostsListView.as_view(), name='developing_posts'),
    path('create/', views.PostCreateView.as_view(), name='blog_create'),
    path('<slug:blog_slug>/', cache_page(60)(views.BlogDetailView.as_view()), name='blog_detail'),
    path('edite/<slug:blog_slug>/', views.ReleasePostUpdateView.as_view(), name='release_post'),
    path('developing_posts/delete/<slug:blog_slug>', views.PostDeleteView.as_view(), name='post_delete'),
    path('activity/<slug:blog_slug>', views.TogglePublishedStatusView.as_view(), name='toggle_published_status'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog import views

app_name = 'catalog'


urlpatterns = [
    path('', views.IndexListView.as_view(), name='homepage'),
    path('contacts/', cache_page(60)(views.ContactsView.as_view()), name='contacts'),
    path('catalog/create/', views.ProductCreateView.as_view(), name='create_product'),
    path('catalog/category/<int:cat_id>', views.show_category, name='show_category'),
    path('catalog/<slug:product_slug>/', views.ToggleSalesStatusView.as_view(), name='toggle_status'),
    path('catalog/view/<slug:product_slug>/', cache_page(60)(views.ProductDetailView.as_view()), name='product_info'),
    path('catalog/delete/<slug:product_slug>', views.ProductDeleteView.as_view(), name='delete_product'),
    path('catalog/edit/<slug:product_slug>/', views.ProductUpdateView.as_view(), name='edit_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('auth/', include('users.urls', namespace='users')),
    path('__debug__/', include("debug_toolbar.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):

    title = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('id',)


class Product(models.Model):

    title = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='images/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    last_change_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f"Наименование товара: {self.title}. " \
               f"Категория: {self.category}. " \
               f"Цена: {self.price}. " \
               f"Дата создания: {self.create_date}"

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('id',)

catalog/models/category.py
from django.db import models
from django.urls import reverse_lazy

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):

    title = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse_lazy('catalog:show_category', kwargs={'cat_id': self.pk})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('pk',)

catalog/models/fashion_blog.py
from django.db import models
from django.urls import reverse_lazy
from slugify import slugify


NULLABLE = {'blank': True, 'null': True}


class FashionBlog(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    content = models.TextField(blank=True, verbose_name='Содержимое')
    image = models.ImageField(upload_to='images/blog', verbose_name='Превью', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return f"Заголовок: {self.title}"

    def get_absolute_url(self):
        return reverse_lazy('catalog:blog_detail', kwargs={'blog_slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блог'
        ordering = ('pk',)

catalog/forms.py
from django import forms
from catalog.models import Product, Version

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CustomNullBooleanSelect(forms.NullBooleanSelect):
    def __init__(self, attrs=None):
        choices = (
            ("unknown", "Не указано"),
            ("true", "Активна"),
            ("false", "Не активна"),
        )
        super().__init__(attrs=attrs)
        self.choices = choices


class CreateProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'description', 'image', 'category', 'price',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'description': forms.Textarea(attrs={'cols': 100, 'rows': 10}),
            'image': forms.FileInput(),
            'price': forms.NumberInput()
        }

    def clean(self):
        cleaned_data = super().clean()
        title = self.cleaned_data['title']
        description = self.cleaned_data['description']

        for word in FORBIDDEN_WORDS:
            if word.lower() in description.lower() or word.lower() in title.lower():
                raise forms.ValidationError('Обнаружены недопустимые слова')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    is_active = forms.BooleanField(widget=CustomNullBooleanSelect, label='Признак активности')

    class Meta:
        model = Version
        fields = '__all__'
        widgets = {
            'version_title': forms.TextInput(attrs={'class': 'form-input'}),
            'version_number': forms.NumberInput(),
        }

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic, View
from catalog.forms import CreateProductForm, VersionForm
from catalog.models import Product, Version


class IndexListView(generic.ListView):
    queryset = Product.objects.all()
    template_name = 'catalog/index.html'
    extra_context = {'title': 'SkyStore', }


class ProductDetailView(generic.DetailView):

    model = Product
    template_name = 'catalog/product_detail.html'
    slug_url_kwarg = 'product_slug'

    def get_queryset(self):
        return Product.objects.filter(slug=self.kwargs['product_slug'])


class ContactsView(generic.TemplateView):
    template_name = 'catalog/contacts.html'


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):

    form_class = CreateProductForm
    template_name = 'catalog/create_product.html'
    permission_required = 'catalog.add_product'

    def get_success_url(self):
        product = self.object
        return reverse('catalog:product_info', args=[product.slug])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)

        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        self.object.product_owner = self.request.user
        self.object.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):

    form_class = CreateProductForm
    template_name = 'catalog/create_product.html'
    slug_url_kwarg = 'product_slug'
    permission_required = 'catalog.change_product'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)

        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_queryset(self):
        return Product.objects.filter(slug=self.kwargs['product_slug'])

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        if self.object.product_owner != self.request.user:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('catalog:edit_product', args=[self.kwargs.get('product_slug')])


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Product
    template_name = 'catalog/confirm_delete_product.html'
    slug_url_kwarg = 'product_slug'
    success_url = reverse_lazy('catalog:homepage')
    permission_required = 'catalog.delete_product'

    def get_queryset(self):
        return Product.objects.filter(slug=self.kwargs['product_slug'])


class ToggleSalesStatusView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'catalog.set_sales_status'

    def get_object(self, queryset=None):
        product_slug = self.kwargs.get('product_slug')
        product = get_object_or_404(Product, slug=product_slug)

        if product.product_owner != self.request.user:
            raise Http404

        return product

    def get(self, request, product_slug):
        product = self.get_object()

        if product.in_stock:
            product.in_stock = False
        else:
            product.in_stock = True
        product.save()

        return redirect(reverse('catalog:homepage'))

catalog/views/dashboard_views.py
from django.views import generic
from catalog.models import Product
from catalog.services import get_category_cache


class IndexListView(generic.ListView):
    queryset = Product.objects.all()
    cats = get_category_cache()
    template_name = 'catalog/index.html'
    extra_context = {'cats': cats,
                     'cat_selected': 0}


class ContactsView(generic.TemplateView):
    template_name = 'catalog/contacts.html'

catalog/views/product_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views import generic
from catalog.forms import CreateProductForm, VersionForm
from catalog.models import Product, Version


class ProductDetailView(generic.DetailView):

    model = Product
    template_name = 'catalog/product_detail.html'
    slug_url_kwarg = 'product_slug'


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):

    form_class = CreateProductForm
    template_name = 'catalog/create_product.html'
    permission_required = 'catalog.add_product'

    def get_success_url(self):
        product = self.object
        return reverse('catalog:product_info', args=[product.slug])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)

        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        self.object.product_owner = self.request.user
        self.object.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):

    form_class = CreateProductForm
    template_name = 'catalog/create_product.html'
    slug_url_kwarg = 'product_slug'
    permission_required = 'catalog.change_product'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)

        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_queryset(self):
        return Product.objects.filter(slug=self.kwargs['product_slug'])

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        if self.object.product_owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('catalog:edit_product', args=[self.kwargs.get('product_slug')])


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Product
    template_name = 'catalog/confirm_delete_product.html'
    slug_url_kwarg = 'product_slug'
    success_url = reverse_lazy('catalog:homepage')
    permission_required = 'catalog.delete_product'

    def get_queryset(self):
        return Product.objects.filter(slug=self.kwargs['product_slug'])

catalog/views/show_category.py
from django.shortcuts import render
from catalog.models import Product, Category
from catalog.services import get_category_cache


def show_category(request, cat_id):
    product = Product.objects.filter(category_id=cat_id)
    cats = get_category_cache()

    context = {
        'product': product,
        'cats': cats,
        'cat_selected': cat_id,
    }

    return render(request, 'catalog/index.html', context=context)

catalog/views/toggle_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View

from catalog.models import Product


class ToggleSalesStatusView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'catalog.set_sales_status'

    def get_object(self, queryset=None):
        product_slug = self.kwargs.get('product_slug')
        product = get_object_or_404(Product, slug=product_slug)

        if product.product_owner != self.request.user:
            raise Http404

        return product

    def get(self, request, product_slug):
        product = self.get_object()

        if product.in_stock:
            product.in_stock = False
        else:
            product.in_stock = True
        product.save()

        return redirect(reverse('catalog:homepage'))

catalog/templates/catalog/confirm_delete_product.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
Удаление товара
{% endblock %}
{% block content %}
<div class="col">
    <div class="d-flex justify-content-around align-items-fluid">
        <div class="container ">
            <div class="card-body card-body-sm ">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-danger">Подтверждение удаления</h4>
                            <h6 class="card-subtitle mb-2">Внимание!</h6>
                            Происходит удаление товара "{{ object.title }}"
                            <p class="card-text">
                                Удаленный товар не подлежит восстановлению, убедитесь в необходимости удаления
                            </p>
                            <button type="submit" class="btn btn-outline-success">Подтвердить удаление</button>
                            <a href="{% url 'catalog:homepage' %}" class="btn btn-outline-primary">Отмена</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block title %}
SkyStore
{% endblock %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>


<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                    <td class="w-25">Страна</td>
                    <td>Россия</td>
                </tr>
                <tr>
                    <td class="w-25">Автор</td>
                    <td>Абрамов Александр</td>
                </tr>
                <tr>
                    <td class="w-25">Адрес</td>
                    <td>Россия, Волгоград</td>
                </tr>
                <tr>
                    <td class="w-25">GitHub</td>
                    <td><a href="https://github.com/Abramov0Alexandr">https://github.com/Abramov0Alexandr</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/create_product.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
{% if object %}
Редактировать товар
{% else %}
Добавить товар
{% endif %}
{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">

    <div class="col-12">
        <div class="d-flex justify-content-around align-items-fluid">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                    Редактирование товара
                    {% else %}
                    Добавление нового товара
                    {% endif %}
                </div>

                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button type="submit" class="btn btn-outline-success">
                        {% if object %}
                        Сохранить изменения
                        {% else %}
                        Добавить товар
                        {% endif %}
                    </button>
                    <a href="{% url 'catalog:homepage' %}" class="btn btn-outline-primary">Назад</a>
                </div>
            </div>

            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        Версия продукта
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
SkyStore
{% endblock %}
{% block content %}


{% for object in object_list %}
<div class="col-12 col-md-4">
    <div class="row mt-3">

        <div class="card mb-4 rounded-3 shadow-sm">

            <div class="d-flex justify-content-around align-items-center">

                <div class="p-2">

                    <img class="rounded mx-auto d-block" src="{{ object.image|upload_media }}" alt="Product Image"
                         width="50%" height="350">

                    <div class="card-body card-body-sm">

                        <div class="card">

                            <p class="card-text"> {{ object.title }}</p>
                            <p class="card-text"> {{ object.description|truncatechars:100 }}</p>
                            <p class="card-text">Стоимость: {{ object.price }} рублей </p>

                            <div class="btn-group btn-group-sm" role="group" aria-label="Button group">
                                {% if not user.is_authenticated %}
                                    <a href="{{ object.get_absolute_url }}" class="btn btn-outline-primary">Посмотреть
                                        товар</a>
                                    {% else %}
                                    <a href="{{ object.get_absolute_url }}" class="btn btn-outline-primary">Посмотреть
                                        товар</a>
                                {% endif %}
                                {% if user.is_superuser or perms.catalog.change_product %}
                                    <a href="{% url 'catalog:edit_product' object.slug %}" class="btn btn-outline-warning">Редактировать</a>
                                {% endif %}
                                {% if user.is_superuser or perms.catalog.set_sales_status %}
                                    {% if object.in_stock %}
                                    <a href="{% url 'catalog:toggle_status' object.slug %}" class="btn btn-outline-warning">Снять
                                        с продажи</a>
                                    {% else %}
                                    <a href="{% url 'catalog:toggle_status' object.slug %}" class="btn btn-outline-warning">Вывести
                                        в продажу</a>
                                    {% endif %}
                                {% endif %}
                                {% if user.is_superuser or perms.catalog.delete_product %}
                                 <a href="{% url 'catalog:delete_product' object.slug %}" class="btn btn-outline-danger">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block title %}
{{ object.title }}
{% endblock %}
{% block content %}
{% if object %}

<div class="col">
    <div class="d-flex justify-content-around align-items-fluid">
        <div class="container ">
            <div class="card-body card-body-sm ">

                <div class="card">
                    <img class="rounded mx-auto d-block" src="{{ object.image|upload_media }}" alt="Product Image"
                         width="30%"
                         height="60%">
                </div>

                <div class="card-body card-body-sm">

                    <article>
                        <p>Наименование товара: {{ object.title }}</p>
                        <p>{{ object.content }}</p>
                        <p>Описание товара: {{ object.description }}</p>
                        <p>Категория товара: {{ object.category }}</p>
                        <p>Стоимость: {{ object.price }}</p>
                        <p>Дата публикации: {{ object.create_date|date:'d.m.Y' }}</p><br>
                        <p>Владелец: {{ object.product_owner|default:"Не указан" }}</p>

                    </article>
                    <a href="{% url 'catalog:homepage' %}" class="btn btn-outline-primary">Назад</a>

                </div>
            </div>
        </div>

        <div class="col-4">
            <div class="container ">
                <div class="card-body card-body-sm ">
                    {% for version in product.version.all %}


                    <p class="card-text">
                        {% if version.is_active %}
                        Активная версия: {{ version.version_title }} |
                        Номер версии: {{ version.version_number}}</p>
                        <hr>
                        {% endif %}
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}